# Generated by Django 4.2.1 on 2023-05-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
