# Generated by Django 4.2.1 on 2023-05-11 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talkshop', '0002_business_slug_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='url',
            new_name='website',
        ),
    ]
