# Generated by Django 4.2.1 on 2023-05-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkshop', '0003_rename_url_business_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='infosource',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='phone',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='business',
            name='price_range',
        ),
        migrations.AddField(
            model_name='business',
            name='tag',
            field=models.CharField(choices=[('All Tags', 'All Tag'), ('Animals', 'Animals'), ('Sports', 'Sports'), ('Gists', 'Gists'), ('Entertainment', 'Entertainment'), ('Health', 'Health')], default='All Tags', max_length=100),
        ),
    ]
