# Generated by Django 4.2.1 on 2023-05-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talkshop', '0006_comment_delete_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
